# Generated by Django 5.2 on 2025-04-02 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('status', models.CharField(choices=[('Watching', 'İzliyorum/Okuyorum'), ('Completed', 'Tamamladım'), ('On Hold', 'Beklemede'), ('Dropped', 'Bıraktım'), ('Plan to Watch', 'İzleyeceğim/Okuyacağım')], default='Plan to Watch', max_length=20, verbose_name='Durum')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Puan (1-10)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Başlama Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitirme Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('cover_image_url', models.URLField(blank=True, null=True, verbose_name='Kapak Resmi URL')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Eklenme Tarihi')),
                ('studio', models.CharField(blank=True, max_length=100, verbose_name='Stüdyo')),
                ('episodes_watched', models.PositiveIntegerField(default=0, verbose_name='İzlenen Bölüm')),
                ('total_episodes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Toplam Bölüm')),
            ],
            options={
                'ordering': ['-added_date', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('status', models.CharField(choices=[('Watching', 'İzliyorum/Okuyorum'), ('Completed', 'Tamamladım'), ('On Hold', 'Beklemede'), ('Dropped', 'Bıraktım'), ('Plan to Watch', 'İzleyeceğim/Okuyacağım')], default='Plan to Watch', max_length=20, verbose_name='Durum')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Puan (1-10)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Başlama Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitirme Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('cover_image_url', models.URLField(blank=True, null=True, verbose_name='Kapak Resmi URL')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Eklenme Tarihi')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Yazar (Mangaka)')),
                ('artist', models.CharField(blank=True, max_length=100, verbose_name='Çizer')),
                ('chapters_read', models.PositiveIntegerField(default=0, verbose_name='Okunan Bölüm')),
                ('volumes_read', models.PositiveIntegerField(default=0, verbose_name='Okunan Cilt')),
                ('total_chapters', models.PositiveIntegerField(blank=True, null=True, verbose_name='Toplam Bölüm')),
                ('total_volumes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Toplam Cilt')),
            ],
            options={
                'ordering': ['-added_date', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('status', models.CharField(choices=[('Watching', 'İzliyorum/Okuyorum'), ('Completed', 'Tamamladım'), ('On Hold', 'Beklemede'), ('Dropped', 'Bıraktım'), ('Plan to Watch', 'İzleyeceğim/Okuyacağım')], default='Plan to Watch', max_length=20, verbose_name='Durum')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Puan (1-10)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Başlama Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitirme Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('cover_image_url', models.URLField(blank=True, null=True, verbose_name='Kapak Resmi URL')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Eklenme Tarihi')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Yazar')),
                ('chapters_read', models.PositiveIntegerField(default=0, verbose_name='Okunan Bölüm')),
                ('volumes_read', models.PositiveIntegerField(default=0, verbose_name='Okunan Cilt')),
                ('total_chapters', models.PositiveIntegerField(blank=True, null=True, verbose_name='Toplam Bölüm')),
                ('total_volumes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Toplam Cilt')),
            ],
            options={
                'ordering': ['-added_date', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('status', models.CharField(choices=[('Watching', 'İzliyorum/Okuyorum'), ('Completed', 'Tamamladım'), ('On Hold', 'Beklemede'), ('Dropped', 'Bıraktım'), ('Plan to Watch', 'İzleyeceğim/Okuyacağım')], default='Plan to Watch', max_length=20, verbose_name='Durum')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Puan (1-10)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Başlama Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitirme Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('cover_image_url', models.URLField(blank=True, null=True, verbose_name='Kapak Resmi URL')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Eklenme Tarihi')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Yazar')),
                ('artist', models.CharField(blank=True, max_length=100, verbose_name='Çizer')),
                ('chapters_read', models.PositiveIntegerField(default=0, verbose_name='Okunan Bölüm')),
                ('total_chapters', models.PositiveIntegerField(blank=True, null=True, verbose_name='Toplam Bölüm')),
                ('platform', models.CharField(blank=True, max_length=100, verbose_name='Platform (Webtoon, Tapas vb.)')),
            ],
            options={
                'ordering': ['-added_date', 'title'],
                'abstract': False,
            },
        ),
    ]
