# Generated by Django 5.2 on 2025-04-03 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_anime_rating_alter_manga_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message="Puan 0'dan küçük olamaz."), django.core.validators.MaxValueValidator(10, message="Puan 10'dan büyük olamaz.")], verbose_name='Puan (0-10)'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message="Puan 0'dan küçük olamaz."), django.core.validators.MaxValueValidator(10, message="Puan 10'dan büyük olamaz.")], verbose_name='Puan (0-10)'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message="Puan 0'dan küçük olamaz."), django.core.validators.MaxValueValidator(10, message="Puan 10'dan büyük olamaz.")], verbose_name='Puan (0-10)'),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message="Puan 0'dan küçük olamaz."), django.core.validators.MaxValueValidator(10, message="Puan 10'dan büyük olamaz.")], verbose_name='Puan (0-10)'),
        ),
    ]
