# Generated by Django 5.2 on 2025-04-04 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_anime_rating_alter_manga_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['user', '-added_date', 'title']},
        ),
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ['user', '-added_date', 'title']},
        ),
        migrations.AlterModelOptions(
            name='novel',
            options={'ordering': ['user', '-added_date', 'title']},
        ),
        migrations.AlterModelOptions(
            name='webtoon',
            options={'ordering': ['user', '-added_date', 'title']},
        ),
        migrations.AddField(
            model_name='anime',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='manga',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='novel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
