# Generated by Django 5.2 on 2025-04-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_anime_user_alter_manga_user_alter_novel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='mangadex_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='MangaDex ID'),
        ),
        migrations.AddField(
            model_name='manga',
            name='mangadex_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='MangaDex ID'),
        ),
        migrations.AddField(
            model_name='novel',
            name='mangadex_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='MangaDex ID'),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='mangadex_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='MangaDex ID'),
        ),
    ]
