# Generated by Django 5.2 on 2025-04-05 02:49

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('tracker', '0007_anime_mangadex_id_manga_mangadex_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Etiketleri virgülle ayırarak giriniz.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Etiketler'),
        ),
        migrations.AddField(
            model_name='manga',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Etiketleri virgülle ayırarak giriniz.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Etiketler'),
        ),
        migrations.AddField(
            model_name='novel',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Etiketleri virgülle ayırarak giriniz.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Etiketler'),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Etiketleri virgülle ayırarak giriniz.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Etiketler'),
        ),
    ]
