# Generated by Django 5.2 on 2025-04-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_anime_tags_manga_tags_novel_tags_webtoon_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='mal_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='MyAnimeList ID'),
        ),
    ]
