# Generated by Django 5.2 on 2025-04-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_anime_mal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='mal_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='MyAnimeList ID'),
        ),
    ]
